name: 'Hello World'
description: 'Greet someone and record the time'
inputs:
  name:  # id of input
    description: 'Name'
    required: true
    default: 'John'
outputs:
  response: # id of output
    description: 'Response'
runs:
  using: 'node16'
  main: 'index.js'